export default  {
  fields: [
        {
            name:"Название ресторана",
            el:"business_name",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
        },
        {
            name:"Адрес ресторана",
            el:"business_address",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
        },
        {
            name:"Город",
            el:"business_city",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
        },
        {
            name:"Штат",
            el:"business_state",
            canEdit:false,
            edit:false,
            sort:-1,
            show: false,
        },
        {
            name:"Телефон",
            el:"business_phone_number",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
        },
        {
            name:"Описание местоположения",
            el:"business_location",
            canEdit:false,
            edit:false,
            sort:-1,
            show: false,
        },
        {
            name:"Почтовый индекс",
            el:"business_postal_code",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
        },
        {
            name:"Дата инспекции",
            el:"inspection_date",
            canEdit:true,
            edit:false,
            date:true,
            sort:-1,
            show: true,
        },
        {
            name:"Статус инспекции",
            el:"inspection_description",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
            select: true,
            selectValue: [
                "NO ACTION",
                "REINSPECTION REQUIRED",
                "SHORTER DATE ADVANCE",
                "ISSUED PERMIT",
            ],
            selected:""
        },
        {
            name:"Тип проведения инспекции",
            el:"inspection_type",
            canEdit:true,
            edit:true,
            sort:-1,
            show: true,
            select: true,
            selectValue: [
                "Regular",
                "Opening",
                "Reinspection",
                "Other",
                "Change of Ownership",
                "Complaint",
                "Enforcement"
            ],
            selected:""
        },
    ]
}